[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd backend && pip install --upgrade pip",
  "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "cd backend && flask db upgrade && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
